firstproject/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name='register'),
]

food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('',views.index,name='index'),
    path('items/',views.item,name='item'),
    path('<int:item_id>/',views.details,name='details'),
    #add items
    path('add',views.create_item,name='create_item'),
    #exit
    path('update/<int:id>/',views.update_item,name='update_item'),
    path('delete/<int:id>/',views.delete_item,name='delete_item'),
]

food/models.py
from django.db import models

# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.item_name
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")
    item_firstname = models.CharField(max_length=200)

users/models.py
from django.db import models

# Create your models here.

food/forms.py
from django import forms 
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

food/views.py
from django.http import HttpResponse
from .models import Item
from django.template import loader
from django.shortcuts import render,redirect
from .forms import ItemForm
# Create your views here.
def index(request):
    item_list = Item.objects.all()
    # template = loader.get_template('food/index.html')
    context={
        'item_list':item_list,
    }
    return render(request,'food/index.html',context)

def item(request):
    return HttpResponse('<h1>HHiiiii</h1>')

def details(request,item_id):
    item = Item.objects.get(pk=item_id)
    context={
        'item':item
    }
    return render(request,'food/details.html',context)

def create_item(request):
    form = ItemForm(request.POST  or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form})

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None,instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from  django.contrib import messages
# Create your views here

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created')
            return redirect('food:index')
    else:
        form = UserCreationForm()
    return render(request,'users/register.html',{'form':form})

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'food/style.css' %}" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    
        <nav class="navbar navbar-dark bg-dark">
            <a href='#' class="navbar-brand"> FoodApp</a>
    
            <div class= "navbar">
                <a class= "nav-item nav-link" href="{%url 'food:create_item' %}">Add Item</a>
                <a class= "nav-item nav-link" href="#">Delete Item</a>
                <a class= "nav-item nav-link" href="#">View Item</a>
            </div>
        </nav>
        {%if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tag }}">{{message}}</div>
                
            {% endfor %}
        {% endif %}
        {% block body  %}{% endblock  %}
    </body>
</html>

food/templates/food/details.html
{% extends "food/base.html" %}
{% block body  %}

<div class = "container">
    <div class= "row">
        <div class ="col-md-6">
            <img height= "300px" src="{{item.item_image}}" class="card" />
        </div>
        <div class ="col-md-6">
            <h1>{{item.item_name}}</h1>
            <h2>{{item.item_desc}}</h2>
            <h2>$ {{item.item_price}}</h2>
            <a href="{% url 'food:delete_item' item.id%}">Delete</a>
        </div>
    </div>
</div>

{% endblock  %}

food/templates/food/index.html
{% extends "food/base.html" %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <!--[if lt IE 7]>
      <p class="browsehappy">
        You are using an <strong>outdated</strong> browser. Please
        <a href="#">upgrade your browser</a> to improve your experience.
      </p>
    <![endif]-->

    {% block body  %}
    {% for item in item_list %}

        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="hard" height="150px" src="{{item.item_image}}"/>
            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name}}</h3>
                <h5>{{item.item_desc}}</h5>
                <h6>$ {{item.item_price}}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:details' item.id%}" class="btn btn-success" >Details</a>
            </div>
        </div>

    {% endfor %}
    {% endblock  %}
  </body>
</html>

food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are You sure you want to delete {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/item-form.html
{%extends 'food/base.html'%}

{%block body%}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>
</form>
{% endblock %}

users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">SignUp</button>
</form>